# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fzXIo6jNW3pOSuTZCqzQ9ejzVWFbJfWu
"""

import plotly
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import csv

datcon = pd.read_csv('covid19_confirmed_global.csv')
datcon.head()

datcon.info()

df = pd.DataFrame(datcon, columns=datrec['Country/Region'])

datcon.describe()

for col in datcon.columns:
    print(col)



from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df)

df_scaled = scaler.transform(df)

covid_df_last_week_columns =datcon.iloc[:,-8:].columns.to_list() 
covid_df_last_week_by_countries = datcon.iloc[:,[1]+[*range(-8,0,1)]] 
top=covid_df_last_week_by_countries.nlargest(n=10, columns=['3/30/22'])
print(top)

top.plot(x="Country/Region", y=["3/24/22", "3/25/22", "3/26/22","3/27/22","3/28/22","3/29/22","3/30/22"], kind="bar")

sns.barplot(x='Country/Region',y='3/23/22',data=top)